-- +migrate Up
INSERT INTO movies (title, poster, synopsis, duration, release_date)
VALUES
    ('Gladiator II', 'https://media.themoviedb.org/t/p/w220_and_h330_face/2cxhvwyEwRlysAmRH4iodkvo0z5.jpg', 'Years after witnessing the death of the revered hero Maximus at the hands of his uncle, Lucius is forced to enter the Colosseum after his home is conquered by the tyrannical Emperors who now lead Rome with an iron fist. With rage in his heart and the future of the Empire at stake, Lucius must look to his past to find strength and honor to return the glory of Rome to its people.', 148, '2024-11-13T00:00:00Z'),
    ('Bila Esok Ibu Tiada', 'https://media.themoviedb.org/t/p/w220_and_h330_face/dUVhcxEPaTw8ns1Q7NgKGdy5ag4.jpg', 'It tells the story of a family with four children consisting of 1 boy and 3 girls. The four children are very dependent on their parents, especially their mother. Until one day, these four siblings had to accept the fate of their mother''s passing.', 104, '2024-11-14T00:00:00Z'),
    ('My Hero Academia: You''re Next', 'https://media.themoviedb.org/t/p/w220_and_h330_face/8rdB1wkheEMMqcY8qLAKjCMPcnZ.jpg', 'In a society devastated by the effects of an all-out war between heroes and villains, a mysterious giant fortress suddenly appears, engulfing towns and people one after another. Then, a man reminiscent of All Might, the ''symbol of peace'', stands in front of Izuku and his friends.', 110, '2024-11-06T00:00:00Z'),
    ('OVERLORD: The Sacred Kingdom', 'https://media.themoviedb.org/t/p/w220_and_h330_face/jEvytxNa5mfW7VAUmDWsZtIdATc.jpg', 'After twelve years of playing his favorite MMORPG game, Momonga logs in for the last time only to find himself transported into its world playing it indefinitely. Throughout his adventures, his avatar ascends to the title of Sorcerer King Ains Ooal Gown. Once prosperous but now on the brink of ruin, The Sacred Kingdom enjoyed years of peace after construction of an enormous wall protecting them from neighboring invasions. But, one day this comes to an end when the Demon Emperor Jaldabaoth arrives with an army of villainous demi-humans. Fearing invasion of their own lands, the neighboring territory of the Slane Theocracy is forced to beg their enemies at the Sorcerer Kingdom for help. Heeding the call, Momonga, now known as the Sorcerer King Ains Ooal Gown, rallies the Sorcerer Kingdom and its undead army to join the fight alongside the Sacred Kingdom and the Slane Theocracy in hopes to defeat the Demon Emperor.', 134, '2024-09-20T00:00:00Z'),
    ('Santet Segoro Pitu', 'https://media.themoviedb.org/t/p/w220_and_h330_face/Aocg0wAqM3XEwRPpL4L4rjkOYJJ.jpg', 'Since his father found a mysterious package and heard the eerie sounds of an indigenous tribe, ARDI and his family have experienced strange events. SUCIPTO (his father), MARNI (his mother), and ARIF (his younger brother) all fell ill, one by one. Ardi and his younger sister, SYIFA, believe this is the result of a santet (a deadly curse), and they will be the next victims. It is a high-level curse from outside the land of Java, known as Santet Segoro Pitu.', 94, '2024-11-07T00:00:00Z'),
    ('Flow', 'https://media.themoviedb.org/t/p/w220_and_h330_face/dzDMewC0Hwv01SROiWgKOi4iOc1.jpg', 'A solitary cat, displaced by a great flood, finds refuge on a boat with various species and must navigate the challenges of adapting to a transformed world together.', 85, '2024-11-08T00:00:00Z'),
    ('Moana 2', 'https://media.themoviedb.org/t/p/w220_and_h330_face/dzDMewC0Hwv01SROiWgKOi4iOc1.jpg', 'After receiving an unexpected call from her wayfinding ancestors, Moana journeys alongside Maui and a new crew to the far seas of Oceania and into dangerous, long-lost waters for an adventure unlike anything she''s ever faced.', 100, '2024-11-27T00:00:00Z'),
    ('Kraven the Hunter', 'https://media.themoviedb.org/t/p/w220_and_h330_face/1GvBhRxY6MELDfxFrete6BNhBB5.jpg', 'Kraven Kravinoff''s complex relationship with his ruthless gangster father, Nikolai, starts him down a path of vengeance with brutal consequences, motivating him to become not only the greatest hunter in the world, but also one of its most feared.', 126, '2024-12-13T00:00:00Z'),
    ('Pantaskah Aku Berhijab', 'https://media.themoviedb.org/t/p/w220_and_h330_face/bGOTGOonRA1kukFrXQgB0i3zD0H.jpg', 'It tells the story of Sofi who lost her father figure in her life. Then he has to face all sorts of trials of life. luckily he has the support of his best friend. Aqsa. Of the various trials, he then questioned whether he was happy, and whether he should wear a hijab.', 114, '2024-11-21T00:00:00Z'),
    ('Daughter''s Daughter', 'https://media.themoviedb.org/t/p/w220_and_h330_face/AeEmC8pIFfzB65LjoAgbA94yFld.jpg', 'Jin is in her 60s. Her husband gone, her concern is for daughter Zuer, in New York trying out IVF with her partner Michelle. When Jin receives news that Zuer and Michelle have died in an accident, she heads for NY. There, she has another shock: she has inherited Zuer’s embryo and it’s for her to decide its fate. Meanwhile, going to NY also forces Jin to face Emma, the daughter she gave up for adoption when she was 17.', 126, '2024-11-20T00:00:00Z'),
    ('Chainsaw Man Movie: Reze-hen', 'https://cdn.myanimelist.net/images/anime/1211/140419.jpg', 'Denji is robbed of a normal teenage life, left with nothing but his deadbeat father''s overwhelming debt. His only companion is his pet, the chainsaw devil Pochita, with whom he slays devils for money that inevitably ends up in the yakuza''s pockets. All Denji can do is dream of a good, simple life: one with delicious food and a beautiful girlfriend by his side. But an act of greedy betrayal by the yakuza leads to Denji''s brutal, untimely death, crushing all hope of him ever achieving happiness', 105, '2024-12-31T00:00:00Z'),
    ('Kimetsu no Yaiba Movie: Mugen Jou-hen', 'https://cdn.myanimelist.net/images/anime/1687/143891.jpg', 'Anime movie trilogy adaptation of the Infinity Castle Arc.', 99, '2025-01-13T00:00:00Z');

INSERT INTO cinemas (name, column_group, number_of_row, disabled_seat)
VALUES
    ('Ao', '{4, 8, 4}', 10, '{"J1","J2","I1","I2","H1","H2","J11","J12","I11","I12","H11","H12"}'),
    ('Aka', '{2, 4, 2}', 10, NULL),
    ('Midori', '{2, 8, 2}', 12, '{"L5","L6","L7","L8","K5","K6","K7","K8","J5","J6","J7","J8","I5","I6","I7","I8"}'),
    ('Murasaki', '{4, 4, 4}', 12, '{"J1","J2","I1","I2","H1","H2","L1","L2","K1","K2"}');

-- +migrate Down